version: '3.1'

services:
    db:
      image: liebberger/mongo_auth:1.0.0
      environment:
        - AUTH=yes
        - MONGODB_ADMIN_USER=admin
        - MONGODB_ADMIN_PASS=tester
        - MONGODB_APPLICATION_DATABASE=sample
        - MONGODB_APPLICATION_USER=thomas
        - MONGODB_APPLICATION_PASS=tester
      ports:
        - "27017:27017"
      volumes:
        - './data:/data/db'


